### ISSUE TITLE
Code Color Scheme Issues in Dark Mode

### ISSUE THREAD

**Issue by ncs-pl** [yelinaung/hugo-blog#1]
Hello.

I recently discovered your articled [*Why My Print Didn't Output Before a Segmentation Fault*](https://blog.yelinaung.com/posts/what-happened-to-my-print/) from [Hacker News](https://news.ycombinator.com/item?id=38803367), and while I did enjoyed the reading, I noticed that the color scheme used for syntax highlighting inside code blocks does not provide enough contrast with the dark gray background, making it difficult to read it.

<img width="677" alt="Screenshot 2024-01-01 at 11 16 25 AM" src="https://github.com/yelinaung/hugo-blog/assets/34602094/949f117f-11a8-43e1-86f5-4d0f47ce8ea5">

In the screenshot, you can notice how function names (`main`, `printf`), variables (`*p`), and pre-processor instructions (`#include <stdio.h>`) need more contrast (tested on both Safari and Google Chrome).

I would suggest using more vibrant colors as well as lighter colors, you may be interested in the [Web Content Accessibility Guideline](https://www.w3.org/TR/WCAG21/) as well.

Once again, great article!

**Comment by yelinaung** [comment]
Hello @nc0fr thanks for letting me know. You are absolutely right. There is an issue with the color scheme in the dark mode. Let me see how I can fix them properly!

**Comment by yelinaung** [comment]
![image](https://github.com/yelinaung/hugo-blog/assets/275120/340d6048-1efd-47d7-9ad7-5f8f589b0b6c)
I tweaked the [pygments](https://pygments.org/) theme a bit and it looks not as bad as before. What do you think ? 😄

**Comment by ncs-pl** [comment]
It surely looks good and is more readable now! Thanks for the change 👍

**Comment by yelinaung** [comment]
thank you and closing this (fixed by https://github.com/yelinaung/hugo-blog/commit/ea9823e8f3b948fdd9cf8f0bb0e0b0c07e1c7899)
